
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'PostYourFun' do

pod 'IQKeyboardManager'
pod 'Alamofire'
pod 'HanekeSwift'
pod 'SwiftyJSON'
pod 'MBProgressHUD'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKMessengerShareKit'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'googleplus-ios-sdk'
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'
pod 'UICKeyChainStore'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'PayPal-iOS-SDK'
pod 'JTSImageViewController'
end